### ISSUE TITLE
Rename modules and executables

### ISSUE THREAD

**Issue by rickyegeland** [lukestegeman/mailsphinx#18]
Rename bin/sphinx.py to bin/mailsphinx.py.  Because why would you call it sphinx.py?

**Comment by rickyegeland** [comment]
I see now that the naming confusion goes deeper.  Executable scripts and module names should have names that make sense for mailsphinx, not just copying the pattern defined by sphinxval (which needs to be reorganized anyway...).

Recommend:  `mailsphinx.sphinx.sphinx` => `mailsphinx`

**Comment by lukestegeman** [comment]
Correct. I started by just lifting the structure of sphinxval. I wanted to rename things in reasonable ways (e.g., change all "sphinx" to "mailsphinx"), but this caused issues with how things were imported and other issues related to `__init__.py`'s contents and location that I didn't bother to figure out. We should discuss your planned future pattern for sphinxval so I can implement it in mailsphinx.

**Comment by lukestegeman** [comment]
Changed the filenames in question. Changing `bin/sphinx.py` to `bin/mailsphinx.py` appears to cause a naming conflict, so `bin/sphinx.py` was renamed to `bin/run_mailsphinx.py`.
